services:
  nginx-frontend:
    build: .
    container_name: nginx-landing
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - attnav-prod
    restart: unless-stopped

  attnav-prod:
    image: attnav:prod
    container_name: attnav-prod
    expose:
      - "80"
    restart: unless-stopped
